### ISSUE TITLE
problems when using optical_flow in iGibson 1.0

### ISSUE THREAD

**Issue by UltronAI** [StanfordVL/iGibson#127]
Hi, I encountered several problems (possibly bugs) after I added optical_flow to sensors. 

I conducted my experiments with iGibson 1. 0 (commit: 893fcda1a1d01ce2da5102d500d2d16f35a62162)

First, I think there is a bug in https://github.com/StanfordVL/iGibson/blob/893fcda1a1d01ce2da5102d500d2d16f35a62162/gibson2/sensors/vision_sensor.py#L108 
 `return raw_vision_obs['optical_flow'][:, :, :3]`
should be 
`return raw_vision_obs['optical_flow'][:, :, :2]`

Second, I find if I want to use optical_flow, I have to change `optimized` to True in [MeshRendererSettings](https://github.com/StanfordVL/iGibson/blob/893fcda1a1d01ce2da5102d500d2d16f35a62162/gibson2/render/mesh_renderer/mesh_renderer_settings.py#L20), otherwise `self.trans_data` and `self.rot_data` in `MeshRenderer` will be None, leading to error for updating dynamic positions with need_flow_info=True. Then, vertices and textures will be optimized when the scene is first loaded. Is it necessary to do this optimization process for rendering optical flow?

Third, I always encounter a  CUDA error after even 1 million frames or more, while this error never occurred when I only used RGB and depth as inputs. 
```
/pytorch/aten/src/THC/THCTensorRandom.cuh:166: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [1,0,0], thread: [0,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
/pytorch/aten/src/THC/THCTensorRandom.cuh:166: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [1,0,0], thread: [1,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
/pytorch/aten/src/THC/THCTensorRandom.cuh:166: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [1,0,0], thread: [2,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
...
RuntimeError: CUDA error: device-side assert triggered
```
And I find it's because there are some nan values in the optical flow. How can I fix this problem?

I'm looking forward to your reply and thank you so much!

**Comment by UltronAI** [comment]
As an alternative method of calculating optical flow, the intrinsic matrix of the realsense camera in the simulator is helpful. If the above issues are difficult to fix, can you provide this info for a quick solution? 

Thanks!

**Comment by roberto-martinmartin** [comment]
@fxia22 , has this been addressed in the newest versions? Should we close this pending issue?

**Comment by fxia22** [comment]
This issue has been fixed.
